// https://github.com/zeplin/zeplin-palette
module.exports = [
    {hex: "#000000", name: "black"},
    {hex: "#000133", name: "very dark blue"},
    {hex: "#00022e", name: "dark navy blue"},
    {hex: "#00035b", name: "dark blue"},
    {hex: "#000435", name: "dark navy"},
    {hex: "#001146", name: "navy blue"},
    {hex: "#002d04", name: "dark forest green"},
    {hex: "#004577", name: "prussian blue"},
    {hex: "#005249", name: "dark blue green"},
    {hex: "#00555a", name: "deep teal"},
    {hex: "#005f6a", name: "petrol"},
    {hex: "#009337", name: "kelley green"},
    {hex: "#00fbb0", name: "greenish turquoise"},
    {hex: "#00ffff", name: "cyan"},
    {hex: "#010fcc", name: "true blue"},
    {hex: "#01153e", name: "navy"},
    {hex: "#01386a", name: "marine blue"},
    {hex: "#014182", name: "darkish blue"},
    {hex: "#014600", name: "racing green"},
    {hex: "#014d4e", name: "dark teal"},
    {hex: "#015482", name: "deep sea blue"},
    {hex: "#0165fc", name: "bright blue"},
    {hex: "#016795", name: "peacock blue"},
    {hex: "#017371", name: "dark aquamarine"},
    {hex: "#017374", name: "deep turquoise"},
    {hex: "#017a79", name: "bluegreen"},
    {hex: "#017b92", name: "ocean"},
    {hex: "#01889f", name: "teal blue"},
    {hex: "#019529", name: "irish green"},
    {hex: "#01a049", name: "emerald"},
    {hex: "#01b44c", name: "shamrock"},
    {hex: "#01c08d", name: "green/blue"},
    {hex: "#01f9c6", name: "bright teal"},
    {hex: "#01ff07", name: "bright green"},
    {hex: "#020035", name: "midnight blue"},
    {hex: "#0203e2", name: "pure blue"},
    {hex: "#02066f", name: "dark royal blue"},
    {hex: "#021bf9", name: "rich blue"},
    {hex: "#02590f", name: "deep green"},
    {hex: "#028f1e", name: "emerald green"},
    {hex: "#029386", name: "teal"},
    {hex: "#02ab2e", name: "kelly green"},
    {hex: "#02c14d", name: "shamrock green"},
    {hex: "#02ccfe", name: "bright sky blue"},
    {hex: "#02d8e9", name: "aqua blue"},
    {hex: "#03012d", name: "midnight"},
    {hex: "#030764", name: "darkblue"},
    {hex: "#030aa7", name: "cobalt blue"},
    {hex: "#033500", name: "dark green"},
    {hex: "#0339f8", name: "vibrant blue"},
    {hex: "#0343df", name: "blue"},
    {hex: "#03719c", name: "ocean blue"},
    {hex: "#040273", name: "deep blue"},
    {hex: "#040348", name: "night blue"},
    {hex: "#042e60", name: "marine"},
    {hex: "#044a05", name: "bottle green"},
    {hex: "#045c5a", name: "dark turquoise"},
    {hex: "#047495", name: "sea blue"},
    {hex: "#048243", name: "jungle green"},
    {hex: "#0485d1", name: "cerulean"},
    {hex: "#04d8b2", name: "aquamarine"},
    {hex: "#04d9ff", name: "neon blue"},
    {hex: "#04f489", name: "turquoise green"},
    {hex: "#0504aa", name: "royal blue"},
    {hex: "#05472a", name: "evergreen"},
    {hex: "#05480d", name: "british racing green"},
    {hex: "#054907", name: "darkgreen"},
    {hex: "#05696b", name: "dark aqua"},
    {hex: "#056eee", name: "cerulean blue"},
    {hex: "#05ffa6", name: "bright sea green"},
    {hex: "#062e03", name: "very dark green"},
    {hex: "#06470c", name: "forest green"},
    {hex: "#0652ff", name: "electric blue"},
    {hex: "#069af3", name: "azure"},
    {hex: "#06b1c4", name: "turquoise blue"},
    {hex: "#06b48b", name: "green blue"},
    {hex: "#06c2ac", name: "turquoise"},
    {hex: "#070d0d", name: "almost black"},
    {hex: "#0804f9", name: "primary blue"},
    {hex: "#08787f", name: "deep aqua"},
    {hex: "#089404", name: "true green"},
    {hex: "#08ff08", name: "fluorescent green"},
    {hex: "#0a437a", name: "twilight blue"},
    {hex: "#0a481e", name: "pine green"},
    {hex: "#0a5f38", name: "spruce"},
    {hex: "#0a888a", name: "dark cyan"},
    {hex: "#0add08", name: "vibrant green"},
    {hex: "#0aff02", name: "fluro green"},
    {hex: "#0b4008", name: "hunter green"},
    {hex: "#0b5509", name: "forest"},
    {hex: "#0b8b87", name: "greenish blue"},
    {hex: "#0bf77d", name: "minty green"},
    {hex: "#0bf9ea", name: "bright aqua"},
    {hex: "#0c06f7", name: "strong blue"},
    {hex: "#0c1793", name: "royal"},
    {hex: "#0cb577", name: "green teal"},
    {hex: "#0cdc73", name: "tealish green"},
    {hex: "#0cff0c", name: "neon green"},
    {hex: "#0d75f8", name: "deep sky blue"},
    {hex: "#0e87cc", name: "water blue"},
    {hex: "#0f9b8e", name: "blue/green"},
    {hex: "#0ffef9", name: "bright turquoise"},
    {hex: "#107ab0", name: "nice blue"},
    {hex: "#10a674", name: "bluish green"},
    {hex: "#11875d", name: "dark sea green"},
    {hex: "#12e193", name: "aqua green"},
    {hex: "#137e6d", name: "blue green"},
    {hex: "#13bbaf", name: "topaz"},
    {hex: "#13eac9", name: "aqua"},
    {hex: "#152eff", name: "vivid blue"},
    {hex: "#154406", name: "forrest green"},
    {hex: "#155084", name: "light navy"},
    {hex: "#15b01a", name: "green"},
    {hex: "#1805db", name: "ultramarine blue"},
    {hex: "#18d17b", name: "seaweed"},
    {hex: "#1b2431", name: "dark"},
    {hex: "#1bfc06", name: "highlighter green"},
    {hex: "#1d0200", name: "very dark brown"},
    {hex: "#1d5dec", name: "azul"},
    {hex: "#1e488f", name: "cobalt"},
    {hex: "#1e9167", name: "viridian"},
    {hex: "#1ef876", name: "spearmint"},
    {hex: "#1f0954", name: "dark indigo"},
    {hex: "#1f3b4d", name: "dark blue grey"},
    {hex: "#1f6357", name: "dark green blue"},
    {hex: "#1fa774", name: "jade"},
    {hex: "#1fb57a", name: "dark seafoam"},
    {hex: "#2000b1", name: "ultramarine"},
    {hex: "#20c073", name: "dark mint green"},
    {hex: "#20f986", name: "wintergreen"},
    {hex: "#2138ab", name: "sapphire"},
    {hex: "#214761", name: "dark slate blue"},
    {hex: "#21c36f", name: "algae green"},
    {hex: "#21fc0d", name: "electric green"},
    {hex: "#2242c7", name: "blue blue"},
    {hex: "#23c48b", name: "greenblue"},
    {hex: "#247afd", name: "clear blue"},
    {hex: "#24bca8", name: "tealish"},
    {hex: "#25a36f", name: "teal green"},
    {hex: "#25ff29", name: "hot green"},
    {hex: "#26538d", name: "dusk blue"},
    {hex: "#26f7fd", name: "bright light blue"},
    {hex: "#276ab3", name: "mid blue"},
    {hex: "#280137", name: "midnight purple"},
    {hex: "#287c37", name: "darkish green"},
    {hex: "#29465b", name: "dark grey blue"},
    {hex: "#2976bb", name: "bluish"},
    {hex: "#2a0134", name: "very dark purple"},
    {hex: "#2a7e19", name: "tree green"},
    {hex: "#2afeb7", name: "greenish cyan"},
    {hex: "#2b5d34", name: "pine"},
    {hex: "#2baf6a", name: "jade green"},
    {hex: "#2bb179", name: "bluey green"},
    {hex: "#2c6fbb", name: "medium blue"},
    {hex: "#2cfa1f", name: "radioactive green"},
    {hex: "#2dfe54", name: "bright light green"},
    {hex: "#2e5a88", name: "light navy blue"},
    {hex: "#2ee8bb", name: "aqua marine"},
    {hex: "#2fef10", name: "vivid green"},
    {hex: "#31668a", name: "ugly blue"},
    {hex: "#32bf84", name: "greenish teal"},
    {hex: "#33b864", name: "cool green"},
    {hex: "#34013f", name: "dark violet"},
    {hex: "#341c02", name: "dark brown"},
    {hex: "#343837", name: "charcoal"},
    {hex: "#35063e", name: "dark purple"},
    {hex: "#35530a", name: "navy green"},
    {hex: "#35ad6b", name: "seaweed green"},
    {hex: "#36013f", name: "deep purple"},
    {hex: "#363737", name: "dark grey"},
    {hex: "#373e02", name: "dark olive"},
    {hex: "#3778bf", name: "windows blue"},
    {hex: "#380282", name: "indigo"},
    {hex: "#380835", name: "eggplant"},
    {hex: "#388004", name: "dark grass green"},
    {hex: "#39ad48", name: "medium green"},
    {hex: "#3a18b1", name: "indigo blue"},
    {hex: "#3a2efe", name: "light royal blue"},
    {hex: "#3ae57f", name: "weird green"},
    {hex: "#3b5b92", name: "denim blue"},
    {hex: "#3b638c", name: "denim"},
    {hex: "#3b719f", name: "muted blue"},
    {hex: "#3c0008", name: "dark maroon"},
    {hex: "#3c4142", name: "charcoal grey"},
    {hex: "#3c4d03", name: "dark olive green"},
    {hex: "#3c73a8", name: "flat blue"},
    {hex: "#3c9992", name: "sea"},
    {hex: "#3d0734", name: "aubergine"},
    {hex: "#3d1c02", name: "chocolate"},
    {hex: "#3d7afd", name: "lightish blue"},
    {hex: "#3d9973", name: "ocean green"},
    {hex: "#3e82fc", name: "dodger blue"},
    {hex: "#3eaf76", name: "dark seafoam green"},
    {hex: "#3f012c", name: "dark plum"},
    {hex: "#3f829d", name: "dirty blue"},
    {hex: "#3f9b0b", name: "grass green"},
    {hex: "#40a368", name: "greenish"},
    {hex: "#40fd14", name: "poison green"},
    {hex: "#410200", name: "deep brown"},
    {hex: "#411900", name: "chocolate brown"},
    {hex: "#419c03", name: "grassy green"},
    {hex: "#41fdfe", name: "bright cyan"},
    {hex: "#42b395", name: "greeny blue"},
    {hex: "#430541", name: "eggplant purple"},
    {hex: "#436bad", name: "french blue"},
    {hex: "#448ee4", name: "dark sky blue"},
    {hex: "#464196", name: "blueberry"},
    {hex: "#475f94", name: "dusky blue"},
    {hex: "#48c072", name: "dark mint"},
    {hex: "#490648", name: "deep violet"},
    {hex: "#49759c", name: "dull blue"},
    {hex: "#4984b8", name: "cool blue"},
    {hex: "#4a0100", name: "mahogany"},
    {hex: "#4b006e", name: "royal purple"},
    {hex: "#4b0101", name: "dried blood"},
    {hex: "#4b57db", name: "warm blue"},
    {hex: "#4b5d16", name: "army green"},
    {hex: "#4b6113", name: "camouflage green"},
    {hex: "#4c9085", name: "dusty teal"},
    {hex: "#4da409", name: "lawn green"},
    {hex: "#4e0550", name: "plum purple"},
    {hex: "#4e518b", name: "twilight"},
    {hex: "#4e5481", name: "dusk"},
    {hex: "#4e7496", name: "cadet blue"},
    {hex: "#4efd54", name: "light neon green"},
    {hex: "#4f738e", name: "metallic blue"},
    {hex: "#4f9153", name: "light forest green"},
    {hex: "#507b9c", name: "stormy blue"},
    {hex: "#50a747", name: "mid green"},
    {hex: "#510ac9", name: "violet blue"},
    {hex: "#516572", name: "slate"},
    {hex: "#5170d7", name: "cornflower blue"},
    {hex: "#51b73b", name: "leafy green"},
    {hex: "#526525", name: "camo green"},
    {hex: "#533cc6", name: "blue with a hint of purple"},
    {hex: "#536267", name: "gunmetal"},
    {hex: "#53fca1", name: "sea green"},
    {hex: "#53fe5c", name: "light bright green"},
    {hex: "#544e03", name: "green brown"},
    {hex: "#548d44", name: "fern green"},
    {hex: "#54ac68", name: "algae"},
    {hex: "#5539cc", name: "blurple"},
    {hex: "#5684ae", name: "off blue"},
    {hex: "#56ae57", name: "dark pastel green"},
    {hex: "#56fca2", name: "light green blue"},
    {hex: "#5729ce", name: "blue purple"},
    {hex: "#580f41", name: "plum"},
    {hex: "#58bc08", name: "frog green"},
    {hex: "#59656d", name: "slate grey"},
    {hex: "#598556", name: "dark sage"},
    {hex: "#5a06ef", name: "blue/purple"},
    {hex: "#5a7d9a", name: "steel blue"},
    {hex: "#5a86ad", name: "dusty blue"},
    {hex: "#5b7c99", name: "slate blue"},
    {hex: "#5c8b15", name: "sap green"},
    {hex: "#5ca904", name: "leaf green"},
    {hex: "#5cac2d", name: "grass"},
    {hex: "#5cb200", name: "kermit green"},
    {hex: "#5d06e9", name: "blue violet"},
    {hex: "#5d1451", name: "grape purple"},
    {hex: "#5d21d0", name: "purple/blue"},
    {hex: "#5e819d", name: "greyish blue"},
    {hex: "#5e9b8a", name: "grey teal"},
    {hex: "#5edc1f", name: "green apple"},
    {hex: "#5f34e7", name: "purpley blue"},
    {hex: "#5f9e8f", name: "dull teal"},
    {hex: "#5fa052", name: "muted green"},
    {hex: "#601ef9", name: "purplish blue"},
    {hex: "#60460f", name: "mud brown"},
    {hex: "#606602", name: "mud green"},
    {hex: "#607c8e", name: "blue grey"},
    {hex: "#610023", name: "burgundy"},
    {hex: "#6140ef", name: "purpleish blue"},
    {hex: "#61de2a", name: "toxic green"},
    {hex: "#61e160", name: "lightish green"},
    {hex: "#6241c7", name: "bluey purple"},
    {hex: "#6258c4", name: "iris"},
    {hex: "#632de9", name: "purple blue"},
    {hex: "#638b27", name: "mossy green"},
    {hex: "#63a950", name: "fern"},
    {hex: "#63b365", name: "boring green"},
    {hex: "#63f7b4", name: "light greenish blue"},
    {hex: "#645403", name: "olive brown"},
    {hex: "#647d8e", name: "grey/blue"},
    {hex: "#6488ea", name: "soft blue"},
    {hex: "#650021", name: "maroon"},
    {hex: "#653700", name: "brown"},
    {hex: "#657432", name: "muddy green"},
    {hex: "#658b38", name: "moss green"},
    {hex: "#658cbb", name: "faded blue"},
    {hex: "#658d6d", name: "slate green"},
    {hex: "#65ab7c", name: "tea"},
    {hex: "#65fe08", name: "bright lime green"},
    {hex: "#661aee", name: "purply blue"},
    {hex: "#665fd1", name: "dark periwinkle"},
    {hex: "#667c3e", name: "military green"},
    {hex: "#667e2c", name: "dirty green"},
    {hex: "#673a3f", name: "purple brown"},
    {hex: "#677a04", name: "olive green"},
    {hex: "#680018", name: "claret"},
    {hex: "#6832e3", name: "burple"},
    {hex: "#696006", name: "greeny brown"},
    {hex: "#696112", name: "greenish brown"},
    {hex: "#698339", name: "swamp"},
    {hex: "#699d4c", name: "flat green"},
    {hex: "#69d84f", name: "fresh green"},
    {hex: "#6a6e09", name: "brownish green"},
    {hex: "#6a79f7", name: "cornflower"},
    {hex: "#6b4247", name: "purplish brown"},
    {hex: "#6b7c85", name: "battleship grey"},
    {hex: "#6b8ba4", name: "grey blue"},
    {hex: "#6ba353", name: "off green"},
    {hex: "#6c3461", name: "grape"},
    {hex: "#6c7a0e", name: "murky green"},
    {hex: "#6d5acf", name: "light indigo"},
    {hex: "#6dedfd", name: "robin's egg"},
    {hex: "#6e1005", name: "reddy brown"},
    {hex: "#6e750e", name: "olive"},
    {hex: "#6ecb3c", name: "apple"},
    {hex: "#6f6c0a", name: "browny green"},
    {hex: "#6f7632", name: "olive drab"},
    {hex: "#6f7c00", name: "poop green"},
    {hex: "#6f828a", name: "steel grey"},
    {hex: "#6fc276", name: "soft green"},
    {hex: "#703be7", name: "bluish purple"},
    {hex: "#706c11", name: "brown green"},
    {hex: "#70b23f", name: "nasty green"},
    {hex: "#719f91", name: "greyish teal"},
    {hex: "#71aa34", name: "leaf"},
    {hex: "#720058", name: "rich purple"},
    {hex: "#728639", name: "khaki green"},
    {hex: "#728f02", name: "dark yellow green"},
    {hex: "#730039", name: "merlot"},
    {hex: "#734a65", name: "dirty purple"},
    {hex: "#735c12", name: "mud"},
    {hex: "#738595", name: "steel"},
    {hex: "#742802", name: "chestnut"},
    {hex: "#748500", name: "swamp green"},
    {hex: "#748b97", name: "bluish grey"},
    {hex: "#749551", name: "drab green"},
    {hex: "#74a662", name: "dull green"},
    {hex: "#750851", name: "velvet"},
    {hex: "#751973", name: "darkish purple"},
    {hex: "#758000", name: "shit green"},
    {hex: "#758da3", name: "blue/grey"},
    {hex: "#75b84f", name: "turtle green"},
    {hex: "#75bbfd", name: "sky blue"},
    {hex: "#75fd63", name: "lighter green"},
    {hex: "#76424e", name: "brownish purple"},
    {hex: "#769958", name: "moss"},
    {hex: "#76a973", name: "dusty green"},
    {hex: "#76cd26", name: "apple green"},
    {hex: "#76fda8", name: "light bluish green"},
    {hex: "#76ff7b", name: "lightgreen"},
    {hex: "#770001", name: "blood"},
    {hex: "#77926f", name: "green grey"},
    {hex: "#77a1b5", name: "greyblue"},
    {hex: "#77ab56", name: "asparagus"},
    {hex: "#789b73", name: "grey green"},
    {hex: "#78d1b6", name: "seafoam blue"},
    {hex: "#7a5901", name: "poop brown"},
    {hex: "#7a687f", name: "purplish grey"},
    {hex: "#7a6a4f", name: "greyish brown"},
    {hex: "#7a9703", name: "ugly green"},
    {hex: "#7af9ab", name: "seafoam green"},
    {hex: "#7b002c", name: "bordeaux"},
    {hex: "#7b0323", name: "wine red"},
    {hex: "#7b5804", name: "shit brown"},
    {hex: "#7bb274", name: "faded green"},
    {hex: "#7bc8f6", name: "lightblue"},
    {hex: "#7bf2da", name: "tiffany blue"},
    {hex: "#7bfdc7", name: "light aquamarine"},
    {hex: "#7d7103", name: "ugly brown"},
    {hex: "#7d7f7c", name: "medium grey"},
    {hex: "#7e1e9c", name: "purple"},
    {hex: "#7e4071", name: "bruise"},
    {hex: "#7ea07a", name: "greeny grey"},
    {hex: "#7ebd01", name: "dark lime green"},
    {hex: "#7ef4cc", name: "light turquoise"},
    {hex: "#7efbb3", name: "light blue green"},
    {hex: "#7f2b0a", name: "reddish brown"},
    {hex: "#7f4e1e", name: "milk chocolate"},
    {hex: "#7f5112", name: "medium brown"},
    {hex: "#7f5e00", name: "poop"},
    {hex: "#7f5f00", name: "shit"},
    {hex: "#7f684e", name: "dark taupe"},
    {hex: "#7f7053", name: "grey brown"},
    {hex: "#7f8f4e", name: "camo"},
    {hex: "#80013f", name: "wine"},
    {hex: "#805b87", name: "muted purple"},
    {hex: "#80f9ad", name: "seafoam"},
    {hex: "#820747", name: "red purple"},
    {hex: "#825f87", name: "dusty purple"},
    {hex: "#826d8c", name: "grey purple"},
    {hex: "#828344", name: "drab"},
    {hex: "#82a67d", name: "greyish green"},
    {hex: "#82cafc", name: "sky"},
    {hex: "#82cbb2", name: "pale teal"},
    {hex: "#836539", name: "dirt brown"},
    {hex: "#840000", name: "dark red"},
    {hex: "#84597e", name: "dull purple"},
    {hex: "#84b701", name: "dark lime"},
    {hex: "#850e04", name: "indian red"},
    {hex: "#856798", name: "dark lavender"},
    {hex: "#85a3b2", name: "bluegrey"},
    {hex: "#866f85", name: "purple grey"},
    {hex: "#86775f", name: "brownish grey"},
    {hex: "#86a17d", name: "grey/green"},
    {hex: "#874c62", name: "dark mauve"},
    {hex: "#8756e4", name: "purpley"},
    {hex: "#875f42", name: "cocoa"},
    {hex: "#876e4b", name: "dull brown"},
    {hex: "#87a922", name: "avocado green"},
    {hex: "#87ae73", name: "sage"},
    {hex: "#87fd05", name: "bright lime"},
    {hex: "#885f01", name: "poo brown"},
    {hex: "#886806", name: "muddy brown"},
    {hex: "#887191", name: "greyish purple"},
    {hex: "#889717", name: "baby shit green"},
    {hex: "#88b378", name: "sage green"},
    {hex: "#894585", name: "light eggplant"},
    {hex: "#895b7b", name: "dusky purple"},
    {hex: "#89a0b0", name: "bluey grey"},
    {hex: "#89a203", name: "vomit green"},
    {hex: "#89fe05", name: "lime green"},
    {hex: "#8a6e45", name: "dirt"},
    {hex: "#8ab8fe", name: "carolina blue"},
    {hex: "#8af1fe", name: "robin egg blue"},
    {hex: "#8b2e16", name: "red brown"},
    {hex: "#8b3103", name: "rust brown"},
    {hex: "#8b88f8", name: "lavender blue"},
    {hex: "#8c000f", name: "crimson"},
    {hex: "#8c0034", name: "red wine"},
    {hex: "#8cfd7e", name: "easter green"},
    {hex: "#8cff9e", name: "baby green"},
    {hex: "#8cffdb", name: "light aqua"},
    {hex: "#8d5eb7", name: "deep lavender"},
    {hex: "#8d8468", name: "brown grey"},
    {hex: "#8e7618", name: "hazel"},
    {hex: "#8e82fe", name: "periwinkle"},
    {hex: "#8eab12", name: "pea green"},
    {hex: "#8ee53f", name: "kiwi green"},
    {hex: "#8f1402", name: "brick red"},
    {hex: "#8f7303", name: "poo"},
    {hex: "#8f8ce7", name: "perrywinkle"},
    {hex: "#8f9805", name: "baby poop green"},
    {hex: "#8f99fb", name: "periwinkle blue"},
    {hex: "#8fae22", name: "icky green"},
    {hex: "#8fb67b", name: "lichen"},
    {hex: "#8ffe09", name: "acid green"},
    {hex: "#8fff9f", name: "mint green"},
    {hex: "#90b134", name: "avocado"},
    {hex: "#90e4c1", name: "light teal"},
    {hex: "#90fda9", name: "foam green"},
    {hex: "#910951", name: "reddish purple"},
    {hex: "#916e99", name: "faded purple"},
    {hex: "#920a4e", name: "mulberry"},
    {hex: "#922b05", name: "brown red"},
    {hex: "#929591", name: "grey"},
    {hex: "#929901", name: "pea soup"},
    {hex: "#937c00", name: "baby poop"},
    {hex: "#94568c", name: "purplish"},
    {hex: "#947706", name: "puke brown"},
    {hex: "#947e94", name: "purpley grey"},
    {hex: "#94a617", name: "pea soup green"},
    {hex: "#94ac02", name: "barf green"},
    {hex: "#94b21c", name: "sickly green"},
    {hex: "#952e8f", name: "warm purple"},
    {hex: "#95a3a6", name: "cool grey"},
    {hex: "#95d0fc", name: "light blue"},
    {hex: "#960056", name: "dark magenta"},
    {hex: "#964e02", name: "warm brown"},
    {hex: "#966ebd", name: "deep lilac"},
    {hex: "#96ae8d", name: "greenish grey"},
    {hex: "#96b403", name: "booger green"},
    {hex: "#96f97b", name: "light green"},
    {hex: "#978a84", name: "warm grey"},
    {hex: "#980002", name: "blood red"},
    {hex: "#983fb2", name: "purply"},
    {hex: "#98568d", name: "purpleish"},
    {hex: "#985e2b", name: "sepia"},
    {hex: "#98eff9", name: "robin's egg blue"},
    {hex: "#98f6b0", name: "light sea green"},
    {hex: "#9900fa", name: "vivid purple"},
    {hex: "#990147", name: "purple red"},
    {hex: "#990f4b", name: "berry"},
    {hex: "#997570", name: "reddish grey"},
    {hex: "#99cc04", name: "slime green"},
    {hex: "#9a0200", name: "deep red"},
    {hex: "#9a0eea", name: "violet"},
    {hex: "#9a3001", name: "auburn"},
    {hex: "#9a6200", name: "raw sienna"},
    {hex: "#9aae07", name: "puke green"},
    {hex: "#9af764", name: "light grass green"},
    {hex: "#9b5fc0", name: "amethyst"},
    {hex: "#9b7a01", name: "yellowish brown"},
    {hex: "#9b8f55", name: "dark khaki"},
    {hex: "#9bb53c", name: "booger"},
    {hex: "#9be5aa", name: "hospital green"},
    {hex: "#9c6d57", name: "brownish"},
    {hex: "#9c6da5", name: "dark lilac"},
    {hex: "#9cbb04", name: "bright olive"},
    {hex: "#9cef43", name: "kiwi"},
    {hex: "#9d0216", name: "carmine"},
    {hex: "#9d0759", name: "dark fuchsia"},
    {hex: "#9d5783", name: "light plum"},
    {hex: "#9d7651", name: "mocha"},
    {hex: "#9db92c", name: "sick green"},
    {hex: "#9dbcd4", name: "light grey blue"},
    {hex: "#9dc100", name: "snot green"},
    {hex: "#9dff00", name: "bright yellow green"},
    {hex: "#9e003a", name: "cranberry"},
    {hex: "#9e0168", name: "red violet"},
    {hex: "#9e3623", name: "brownish red"},
    {hex: "#9e43a2", name: "medium purple"},
    {hex: "#9f2305", name: "burnt red"},
    {hex: "#9f8303", name: "diarrhea"},
    {hex: "#9ffeb0", name: "mint"},
    {hex: "#a0025c", name: "deep magenta"},
    {hex: "#a00498", name: "barney purple"},
    {hex: "#a03623", name: "brick"},
    {hex: "#a0450e", name: "burnt umber"},
    {hex: "#a0bf16", name: "gross green"},
    {hex: "#a0febf", name: "light seafoam"},
    {hex: "#a13905", name: "russet"},
    {hex: "#a24857", name: "light maroon"},
    {hex: "#a2653e", name: "earth"},
    {hex: "#a2a415", name: "vomit"},
    {hex: "#a2bffe", name: "pastel blue"},
    {hex: "#a2cffe", name: "baby blue"},
    {hex: "#a442a0", name: "ugly purple"},
    {hex: "#a484ac", name: "heather"},
    {hex: "#a4be5c", name: "light olive green"},
    {hex: "#a4bf20", name: "pea"},
    {hex: "#a50055", name: "violet red"},
    {hex: "#a552e6", name: "lightish purple"},
    {hex: "#a55af4", name: "lighter purple"},
    {hex: "#a57e52", name: "puce"},
    {hex: "#a5a391", name: "cement"},
    {hex: "#a5a502", name: "puke"},
    {hex: "#a5fbd5", name: "pale turquoise"},
    {hex: "#a66fb5", name: "soft purple"},
    {hex: "#a6814c", name: "coffee"},
    {hex: "#a6c875", name: "light moss green"},
    {hex: "#a6fbb2", name: "light mint green"},
    {hex: "#a75e09", name: "raw umber"},
    {hex: "#a7ffb5", name: "light seafoam green"},
    {hex: "#a83c09", name: "rust"},
    {hex: "#a8415b", name: "light burgundy"},
    {hex: "#a87900", name: "bronze"},
    {hex: "#a87dc2", name: "wisteria"},
    {hex: "#a88905", name: "dark mustard"},
    {hex: "#a88f59", name: "dark sand"},
    {hex: "#a8a495", name: "greyish"},
    {hex: "#a8b504", name: "mustard green"},
    {hex: "#a8ff04", name: "electric lime"},
    {hex: "#a90308", name: "darkish red"},
    {hex: "#a9561e", name: "sienna"},
    {hex: "#a9be70", name: "tan green"},
    {hex: "#a9f971", name: "spring green"},
    {hex: "#aa23ff", name: "electric purple"},
    {hex: "#aa2704", name: "rust red"},
    {hex: "#aaa662", name: "khaki"},
    {hex: "#aaff32", name: "lime"},
    {hex: "#ab1239", name: "rouge"},
    {hex: "#ab7e4c", name: "tan brown"},
    {hex: "#ab9004", name: "baby poo"},
    {hex: "#ac1db8", name: "barney"},
    {hex: "#ac4f06", name: "cinnamon"},
    {hex: "#ac7434", name: "leather"},
    {hex: "#ac7e04", name: "mustard brown"},
    {hex: "#ac86a8", name: "dusty lavender"},
    {hex: "#ac9362", name: "dark beige"},
    {hex: "#acbb0d", name: "snot"},
    {hex: "#acbf69", name: "light olive"},
    {hex: "#acc2d9", name: "cloudy blue"},
    {hex: "#acfffc", name: "light cyan"},
    {hex: "#ad03de", name: "vibrant purple"},
    {hex: "#ad0afd", name: "bright violet"},
    {hex: "#ad8150", name: "light brown"},
    {hex: "#ad900d", name: "baby shit brown"},
    {hex: "#ada587", name: "stone"},
    {hex: "#adf802", name: "lemon green"},
    {hex: "#ae7181", name: "mauve"},
    {hex: "#ae8b0c", name: "yellowy brown"},
    {hex: "#aefd6c", name: "light lime"},
    {hex: "#aeff6e", name: "key lime"},
    {hex: "#af2f0d", name: "rusty red"},
    {hex: "#af6f09", name: "caramel"},
    {hex: "#af884a", name: "dark tan"},
    {hex: "#afa88b", name: "bland"},
    {hex: "#b00149", name: "raspberry"},
    {hex: "#b0054b", name: "purplish red"},
    {hex: "#b04e0f", name: "burnt sienna"},
    {hex: "#b0dd16", name: "yellowish green"},
    {hex: "#b0ff9d", name: "pastel green"},
    {hex: "#b16002", name: "orangey brown"},
    {hex: "#b17261", name: "pinkish brown"},
    {hex: "#b1916e", name: "pale brown"},
    {hex: "#b1d1fc", name: "powder blue"},
    {hex: "#b1d27b", name: "pale olive green"},
    {hex: "#b1fc99", name: "pale light green"},
    {hex: "#b1ff65", name: "pale lime green"},
    {hex: "#b25f03", name: "orangish brown"},
    {hex: "#b26400", name: "umber"},
    {hex: "#b2713d", name: "clay brown"},
    {hex: "#b27a01", name: "golden brown"},
    {hex: "#b29705", name: "brown yellow"},
    {hex: "#b2996e", name: "dust"},
    {hex: "#b2fba5", name: "light pastel green"},
    {hex: "#b36ff6", name: "light urple"},
    {hex: "#b5485d", name: "dark rose"},
    {hex: "#b59410", name: "dark gold"},
    {hex: "#b5c306", name: "bile"},
    {hex: "#b5ce08", name: "green/yellow"},
    {hex: "#b66325", name: "copper"},
    {hex: "#b66a50", name: "clay"},
    {hex: "#b6c406", name: "baby puke green"},
    {hex: "#b6ffbb", name: "light mint"},
    {hex: "#b75203", name: "burnt siena"},
    {hex: "#b790d4", name: "pale purple"},
    {hex: "#b79400", name: "yellow brown"},
    {hex: "#b7c9e2", name: "light blue grey"},
    {hex: "#b7e1a1", name: "light grey green"},
    {hex: "#b7fffa", name: "pale cyan"},
    {hex: "#b8ffeb", name: "pale aqua"},
    {hex: "#b9484e", name: "dusty red"},
    {hex: "#b96902", name: "brown orange"},
    {hex: "#b9a281", name: "taupe"},
    {hex: "#b9cc81", name: "pale olive"},
    {hex: "#b9ff66", name: "light lime green"},
    {hex: "#ba6873", name: "dusky rose"},
    {hex: "#ba9e88", name: "mushroom"},
    {hex: "#bb3f3f", name: "dull red"},
    {hex: "#bbf90f", name: "yellowgreen"},
    {hex: "#bc13fe", name: "neon purple"},
    {hex: "#bccb7a", name: "greenish tan"},
    {hex: "#bcecac", name: "light sage"},
    {hex: "#bcf5a6", name: "washed out green"},
    {hex: "#bd6c48", name: "adobe"},
    {hex: "#bdf6fe", name: "pale sky blue"},
    {hex: "#bdf8a3", name: "tea green"},
    {hex: "#be0119", name: "scarlet"},
    {hex: "#be013c", name: "rose red"},
    {hex: "#be03fd", name: "bright purple"},
    {hex: "#be6400", name: "orange brown"},
    {hex: "#beae8a", name: "putty"},
    {hex: "#befd73", name: "pale lime"},
    {hex: "#befdb7", name: "celadon"},
    {hex: "#bf77f6", name: "light purple"},
    {hex: "#bf9005", name: "ochre"},
    {hex: "#bf9b0c", name: "ocher"},
    {hex: "#bfac05", name: "muddy yellow"},
    {hex: "#bff128", name: "yellowy green"},
    {hex: "#bffe28", name: "lemon lime"},
    {hex: "#c0022f", name: "lipstick red"},
    {hex: "#c04e01", name: "burnt orange"},
    {hex: "#c071fe", name: "easter purple"},
    {hex: "#c0737a", name: "dusty rose"},
    {hex: "#c0fa8b", name: "pistachio"},
    {hex: "#c0fb2d", name: "yellow green"},
    {hex: "#c14a09", name: "brick orange"},
    {hex: "#c1c6fc", name: "light periwinkle"},
    {hex: "#c1f80a", name: "chartreuse"},
    {hex: "#c1fd95", name: "celery"},
    {hex: "#c20078", name: "magenta"},
    {hex: "#c27e79", name: "brownish pink"},
    {hex: "#c292a1", name: "light mauve"},
    {hex: "#c2b709", name: "olive yellow"},
    {hex: "#c2be0e", name: "puke yellow"},
    {hex: "#c2ff89", name: "light yellowish green"},
    {hex: "#c3909b", name: "grey pink"},
    {hex: "#c3fbf4", name: "duck egg blue"},
    {hex: "#c44240", name: "reddish"},
    {hex: "#c45508", name: "rust orange"},
    {hex: "#c48efd", name: "liliac"},
    {hex: "#c4a661", name: "sandy brown"},
    {hex: "#c4fe82", name: "light pea green"},
    {hex: "#c4fff7", name: "eggshell blue"},
    {hex: "#c5c9c7", name: "silver"},
    {hex: "#c65102", name: "dark orange"},
    {hex: "#c69c04", name: "ocre"},
    {hex: "#c69f59", name: "camel"},
    {hex: "#c6f808", name: "greeny yellow"},
    {hex: "#c6fcff", name: "light sky blue"},
    {hex: "#c74767", name: "deep rose"},
    {hex: "#c760ff", name: "bright lavender"},
    {hex: "#c77986", name: "old pink"},
    {hex: "#c79fef", name: "lavender"},
    {hex: "#c7ac7d", name: "toupe"},
    {hex: "#c7c10c", name: "vomit yellow"},
    {hex: "#c7fdb5", name: "pale green"},
    {hex: "#c83cb9", name: "purpley pink"},
    {hex: "#c85a53", name: "dark salmon"},
    {hex: "#c875c4", name: "orchid"},
    {hex: "#c87606", name: "dirty orange"},
    {hex: "#c87f89", name: "old rose"},
    {hex: "#c88d94", name: "greyish pink"},
    {hex: "#c8aca9", name: "pinkish grey"},
    {hex: "#c8fd3d", name: "yellow/green"},
    {hex: "#c8ffb0", name: "light light green"},
    {hex: "#c94cbe", name: "pinky purple"},
    {hex: "#c95efb", name: "bright lilac"},
    {hex: "#c9643b", name: "terra cotta"},
    {hex: "#c9ae74", name: "sandstone"},
    {hex: "#c9b003", name: "brownish yellow"},
    {hex: "#c9d179", name: "greenish beige"},
    {hex: "#c9ff27", name: "green yellow"},
    {hex: "#ca0147", name: "ruby"},
    {hex: "#ca6641", name: "terracotta"},
    {hex: "#ca6b02", name: "browny orange"},
    {hex: "#ca7b80", name: "dirty pink"},
    {hex: "#ca9bf7", name: "baby purple"},
    {hex: "#caa0ff", name: "pastel purple"},
    {hex: "#cafffb", name: "light light blue"},
    {hex: "#cb00f5", name: "hot purple"},
    {hex: "#cb0162", name: "deep pink"},
    {hex: "#cb416b", name: "dark pink"},
    {hex: "#cb6843", name: "terracota"},
    {hex: "#cb7723", name: "brownish orange"},
    {hex: "#cb9d06", name: "yellow ochre"},
    {hex: "#cba560", name: "sand brown"},
    {hex: "#cbf85f", name: "pear"},
    {hex: "#cc7a8b", name: "dusky pink"},
    {hex: "#ccad60", name: "desert"},
    {hex: "#ccfd7f", name: "light yellow green"},
    {hex: "#cd5909", name: "rusty orange"},
    {hex: "#cd7584", name: "ugly pink"},
    {hex: "#cdc50a", name: "dirty yellow"},
    {hex: "#cdfd02", name: "greenish yellow"},
    {hex: "#ce5dae", name: "purplish pink"},
    {hex: "#cea2fd", name: "lilac"},
    {hex: "#ceaefa", name: "pale violet"},
    {hex: "#ceb301", name: "mustard"},
    {hex: "#cf0234", name: "cherry"},
    {hex: "#cf524e", name: "dark coral"},
    {hex: "#cf6275", name: "rose"},
    {hex: "#cfaf7b", name: "fawn"},
    {hex: "#cffdbc", name: "very pale green"},
    {hex: "#cfff04", name: "neon yellow"},
    {hex: "#d0c101", name: "ugly yellow"},
    {hex: "#d0e429", name: "sickly yellow"},
    {hex: "#d0fe1d", name: "lime yellow"},
    {hex: "#d0fefe", name: "pale blue"},
    {hex: "#d1768f", name: "muted pink"},
    {hex: "#d1b26f", name: "tan"},
    {hex: "#d1ffbd", name: "very light green"},
    {hex: "#d2bd0a", name: "mustard yellow"},
    {hex: "#d3494e", name: "faded red"},
    {hex: "#d3b683", name: "very light brown"},
    {hex: "#d46a7e", name: "pinkish"},
    {hex: "#d4ffff", name: "really light blue"},
    {hex: "#d5174e", name: "lipstick"},
    {hex: "#d5869d", name: "dull pink"},
    {hex: "#d58a94", name: "dusty pink"},
    {hex: "#d5ab09", name: "burnt yellow"},
    {hex: "#d5b60a", name: "dark yellow"},
    {hex: "#d5ffff", name: "very light blue"},
    {hex: "#d648d7", name: "pinkish purple"},
    {hex: "#d6b4fc", name: "light violet"},
    {hex: "#d6fffa", name: "ice"},
    {hex: "#d6fffe", name: "very pale blue"},
    {hex: "#d725de", name: "purple/pink"},
    {hex: "#d767ad", name: "pale magenta"},
    {hex: "#d7fffe", name: "ice blue"},
    {hex: "#d8863b", name: "dull orange"},
    {hex: "#d8dcd6", name: "light grey"},
    {hex: "#d90166", name: "dark hot pink"},
    {hex: "#d94ff5", name: "heliotrope"},
    {hex: "#d9544d", name: "pale red"},
    {hex: "#d99b82", name: "pinkish tan"},
    {hex: "#da467d", name: "darkish pink"},
    {hex: "#db4bda", name: "pink purple"},
    {hex: "#db5856", name: "pastel red"},
    {hex: "#dbb40c", name: "gold"},
    {hex: "#dc4d01", name: "deep orange"},
    {hex: "#dd85d7", name: "lavender pink"},
    {hex: "#ddd618", name: "piss yellow"},
    {hex: "#de0c62", name: "cerise"},
    {hex: "#de7e5d", name: "dark peach"},
    {hex: "#de9dac", name: "faded pink"},
    {hex: "#df4ec8", name: "purpleish pink"},
    {hex: "#dfc5fe", name: "light lavender"},
    {hex: "#e03fd8", name: "purple pink"},
    {hex: "#e17701", name: "pumpkin"},
    {hex: "#e2ca76", name: "sand"},
    {hex: "#e4cbff", name: "pale lilac"},
    {hex: "#e50000", name: "red"},
    {hex: "#e6daa6", name: "beige"},
    {hex: "#e6f2a2", name: "light khaki"},
    {hex: "#e78ea5", name: "pig pink"},
    {hex: "#ec2d01", name: "tomato red"},
    {hex: "#ed0dd9", name: "fuchsia"},
    {hex: "#edc8ff", name: "light lilac"},
    {hex: "#eecffe", name: "pale lavender"},
    {hex: "#eedc5b", name: "dull yellow"},
    {hex: "#ef1de7", name: "pink/purple"},
    {hex: "#ef4026", name: "tomato"},
    {hex: "#efb435", name: "macaroni and cheese"},
    {hex: "#efc0fe", name: "light lavendar"},
    {hex: "#f075e6", name: "purply pink"},
    {hex: "#f0833a", name: "dusty orange"},
    {hex: "#f0944d", name: "faded orange"},
    {hex: "#f10c45", name: "pinkish red"},
    {hex: "#f1da7a", name: "sandy"},
    {hex: "#f1f33f", name: "off yellow"},
    {hex: "#f29e8e", name: "blush"},
    {hex: "#f2ab15", name: "squash"},
    {hex: "#f36196", name: "medium pink"},
    {hex: "#f4320c", name: "vermillion"},
    {hex: "#f43605", name: "orangish red"},
    {hex: "#f4d054", name: "maize"},
    {hex: "#f504c9", name: "hot magenta"},
    {hex: "#f5054f", name: "pink red"},
    {hex: "#f5bf03", name: "golden"},
    {hex: "#f6688e", name: "rosy pink"},
    {hex: "#f6cefc", name: "very light purple"},
    {hex: "#f7022a", name: "cherry red"},
    {hex: "#f7879a", name: "rose pink"},
    {hex: "#f7d560", name: "light mustard"},
    {hex: "#f8481c", name: "reddish orange"},
    {hex: "#f97306", name: "orange"},
    {hex: "#f9bc08", name: "golden rod"},
    {hex: "#fa2a55", name: "red pink"},
    {hex: "#fa4224", name: "orangey red"},
    {hex: "#fa5ff7", name: "light magenta"},
    {hex: "#fac205", name: "goldenrod"},
    {hex: "#faee66", name: "yellowish"},
    {hex: "#fafe4b", name: "banana yellow"},
    {hex: "#fb2943", name: "strawberry"},
    {hex: "#fb5581", name: "warm pink"},
    {hex: "#fb5ffc", name: "violet pink"},
    {hex: "#fb7d07", name: "pumpkin orange"},
    {hex: "#fbdd7e", name: "wheat"},
    {hex: "#fbeeac", name: "light tan"},
    {hex: "#fc2647", name: "pinky red"},
    {hex: "#fc5a50", name: "coral"},
    {hex: "#fc824a", name: "orangish"},
    {hex: "#fc86aa", name: "pinky"},
    {hex: "#fcb001", name: "yellow orange"},
    {hex: "#fcc006", name: "marigold"},
    {hex: "#fce166", name: "sand yellow"},
    {hex: "#fcf679", name: "straw"},
    {hex: "#fcfc81", name: "yellowish tan"},
    {hex: "#fd3c06", name: "red orange"},
    {hex: "#fd411e", name: "orange red"},
    {hex: "#fd4659", name: "watermelon"},
    {hex: "#fd5956", name: "grapefruit"},
    {hex: "#fd798f", name: "carnation"},
    {hex: "#fd8d49", name: "orangeish"},
    {hex: "#fdaa48", name: "light orange"},
    {hex: "#fdb0c0", name: "soft pink"},
    {hex: "#fdb147", name: "butterscotch"},
    {hex: "#fdb915", name: "orangey yellow"},
    {hex: "#fdc1c5", name: "pale rose"},
    {hex: "#fddc5c", name: "light gold"},
    {hex: "#fdde6c", name: "pale gold"},
    {hex: "#fdee73", name: "sandy yellow"},
    {hex: "#fdfdfe", name: "pale grey"},
    {hex: "#fdff38", name: "lemon yellow"},
    {hex: "#fdff52", name: "lemon"},
    {hex: "#fdff63", name: "canary"},
    {hex: "#fe0002", name: "fire engine red"},
    {hex: "#fe019a", name: "neon pink"},
    {hex: "#fe01b1", name: "bright pink"},
    {hex: "#fe02a2", name: "shocking pink"},
    {hex: "#fe2c54", name: "reddish pink"},
    {hex: "#fe2f4a", name: "lightish red"},
    {hex: "#fe420f", name: "orangered"},
    {hex: "#fe46a5", name: "barbie pink"},
    {hex: "#fe4b03", name: "blood orange"},
    {hex: "#fe7b7c", name: "salmon pink"},
    {hex: "#fe828c", name: "blush pink"},
    {hex: "#fe83cc", name: "bubblegum pink"},
    {hex: "#fe86a4", name: "rosa"},
    {hex: "#fea993", name: "light salmon"},
    {hex: "#feb209", name: "saffron"},
    {hex: "#feb308", name: "amber"},
    {hex: "#fec615", name: "golden yellow"},
    {hex: "#fed0fc", name: "pale mauve"},
    {hex: "#fedf08", name: "dandelion"},
    {hex: "#fef69e", name: "buff"},
    {hex: "#fefcaf", name: "parchment"},
    {hex: "#feff7f", name: "faded yellow"},
    {hex: "#feffca", name: "ecru"},
    {hex: "#ff000d", name: "bright red"},
    {hex: "#ff028d", name: "hot pink"},
    {hex: "#ff0490", name: "electric pink"},
    {hex: "#ff073a", name: "neon red"},
    {hex: "#ff0789", name: "strong pink"},
    {hex: "#ff08e8", name: "bright magenta"},
    {hex: "#ff474c", name: "light red"},
    {hex: "#ff5b00", name: "bright orange"},
    {hex: "#ff6163", name: "coral pink"},
    {hex: "#ff63e9", name: "candy pink"},
    {hex: "#ff69af", name: "bubble gum pink"},
    {hex: "#ff6cb5", name: "bubblegum"},
    {hex: "#ff6f52", name: "orange pink"},
    {hex: "#ff724c", name: "pinkish orange"},
    {hex: "#ff7855", name: "melon"},
    {hex: "#ff796c", name: "salmon"},
    {hex: "#ff7fa7", name: "carnation pink"},
    {hex: "#ff81c0", name: "pink"},
    {hex: "#ff9408", name: "tangerine"},
    {hex: "#ff964f", name: "pastel orange"},
    {hex: "#ff9a8a", name: "peachy pink"},
    {hex: "#ffa62b", name: "mango"},
    {hex: "#ffa756", name: "pale orange"},
    {hex: "#ffab0f", name: "yellowish orange"},
    {hex: "#ffad01", name: "orange yellow"},
    {hex: "#ffb07c", name: "peach"},
    {hex: "#ffb16d", name: "apricot"},
    {hex: "#ffb19a", name: "pale salmon"},
    {hex: "#ffb2d0", name: "powder pink"},
    {hex: "#ffb7ce", name: "baby pink"},
    {hex: "#ffbacd", name: "pastel pink"},
    {hex: "#ffc512", name: "sunflower"},
    {hex: "#ffc5cb", name: "light rose"},
    {hex: "#ffcfdc", name: "pale pink"},
    {hex: "#ffd1df", name: "light pink"},
    {hex: "#ffd8b1", name: "light peach"},
    {hex: "#ffda03", name: "sunflower yellow"},
    {hex: "#ffdf22", name: "sun yellow"},
    {hex: "#ffe36e", name: "yellow tan"},
    {hex: "#ffe5ad", name: "pale peach"},
    {hex: "#fff39a", name: "dark cream"},
    {hex: "#fff4f2", name: "very light pink"},
    {hex: "#fff917", name: "sunny yellow"},
    {hex: "#fff9d0", name: "pale"},
    {hex: "#fffa86", name: "manilla"},
    {hex: "#fffcc4", name: "egg shell"},
    {hex: "#fffd01", name: "bright yellow"},
    {hex: "#fffd37", name: "sunshine yellow"},
    {hex: "#fffd74", name: "butter yellow"},
    {hex: "#fffd78", name: "custard"},
    {hex: "#fffe40", name: "canary yellow"},
    {hex: "#fffe71", name: "pastel yellow"},
    {hex: "#fffe7a", name: "light yellow"},
    {hex: "#fffeb6", name: "light beige"},
    {hex: "#ffff14", name: "yellow"},
    {hex: "#ffff7e", name: "banana"},
    {hex: "#ffff81", name: "butter"},
    {hex: "#ffff84", name: "pale yellow"},
    {hex: "#ffffb6", name: "creme"},
    {hex: "#ffffc2", name: "cream"},
    {hex: "#ffffcb", name: "ivory"},
    {hex: "#ffffd4", name: "eggshell"},
    {hex: "#ffffe4", name: "off white"},
    {hex: "#ffffff", name: "white"}
]
